FinanceManagementApi/Controllers/ComplaintController.cs
using FinanceManagementApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinanceManagementApi.Controllers
{
    public class ComplaintController : Controller
    {

        // GET: Member
        FinanceManagementAPIEntities finance = new FinanceManagementAPIEntities();

        public ActionResult viewComplaints()
        {
            return View(finance.ComplaintRecords.ToList());
        }

        // GET: Member/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Member/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Member/Create
        [HttpPost]
        public ActionResult Create(ComplaintRecord complaintRecord)
        {
            if (!ModelState.IsValid)
                return View();
            finance.ComplaintRecords.Add(complaintRecord);
            finance.SaveChanges();
            //Response.Redirect("StudentAdmission",true);
            return View();

        }

        // GET: Member/Edit/5
        public ActionResult Edit(int id)
        {

            var IdToEdit = (from m in finance.ComplaintRecords where m.ID == id select m).First();
            return View(IdToEdit);
        }

        // POST: Member/Edit/5
        [HttpPost]
        public ActionResult Edit(ComplaintRecord complaintRecord)
        {

            var orignalRecord = (from m in finance.ComplaintRecords where m.ID == complaintRecord.ID select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            finance.Entry(orignalRecord).CurrentValues.SetValues(complaintRecord);

            finance.SaveChanges();
            return RedirectToAction("viewComplaints");
        }

        // GET: Member/Delete/5
        public ActionResult Delete(ComplaintRecord complaintRecord)
        {
            var d = finance.ComplaintRecords.Where(x => x.ID == complaintRecord.ID).FirstOrDefault();
            finance.ComplaintRecords.Remove(d);
            finance.SaveChanges();
            return RedirectToAction("viewComplaints");
        }

        // POST: Member/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


    }
}

FinanceManagementApi/Controllers/HeadController.cs
using FinanceManagementApi.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinanceManagementApi.Controllers
{
    public class HeadController : Controller
    {
        // GET: Head
        BackendClass backendClass = new BackendClass();

        public ActionResult HeadLogin()
        {
            return View();
        }
        public ActionResult tryAgain()
        {
            return View();
        }
        public ActionResult welcome()
        {
            return View();
        }

        [HttpPost]
        public ActionResult head_logincheck(Head_class Login)
        {
            //generate the query to check the user name or passwod
            String qry = "select * from Head_Login where Head_Name='" + Login.head_Name + "' and Head_Password='" + Login.head_Password + "'";
            DataTable tbl = new DataTable();

            int x =backendClass.Head_LoginCheck(qry);
            if (x > 0)
            {
                return View("welcome");
            }
            else
            {
                return View("tryAgain");
            }


        }


    }
}

FinanceManagementApi/Controllers/ServicesController.cs
using FinanceManagementApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinanceManagementApi.Controllers
{
    public class ServicesController : Controller
    {

        // GET: Member
        FinanceManagementAPIEntities finance = new FinanceManagementAPIEntities();

        public ActionResult viewServices()
        {
            return View(finance.ServiceRecords.ToList());
        }


        public ActionResult userServices()
        {
            return View(finance.ServiceRecords.ToList());
        }


        // GET: Member/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Member/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Member/Create
        [HttpPost]
        public ActionResult Create(ServiceRecord serviceRecord)
        {
            if (!ModelState.IsValid)
                return View();
            finance.ServiceRecords.Add(serviceRecord);
            finance.SaveChanges();
            //Response.Redirect("StudentAdmission",true);
            return RedirectToAction("viewServices");

        }

        // GET: Member/Edit/5
        public ActionResult Edit(int id)
        {

            var IdToEdit = (from m in finance.ServiceRecords where m.ID == id select m).First();
            return View(IdToEdit);
        }

        // POST: Member/Edit/5
        [HttpPost]
        public ActionResult Edit(ServiceRecord serviceRecord)
        {

            var orignalRecord = (from m in finance.ServiceRecords where m.ID == serviceRecord.ID select m).First();

            if (!ModelState.IsValid)
                return View(orignalRecord);
            finance.Entry(orignalRecord).CurrentValues.SetValues(serviceRecord);

            finance.SaveChanges();
            return RedirectToAction("viewServices");
        }

        // GET: Member/Delete/5
        public ActionResult Delete(StaffMemberRecord staffMember)
        {
            var d = finance.StaffMemberRecords.Where(x => x.ID == staffMember.ID).FirstOrDefault();
            finance.StaffMemberRecords.Remove(d);
            finance.SaveChanges();
            return RedirectToAction("RegisteredStaffMember");
        }

        // POST: Member/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

FinanceManagementApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="//fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <!-- //web fonts -->
    <!-- Template CSS -->
    <link rel="stylesheet" href="~/assets/css/style-starter.css">
</head>
<body>
    <section class="w3l-bootstrap-header">
        <nav class="navbar navbar-expand-lg navbar-light py-lg-2 py-2">
            <div class="container">
                <a class="navbar-brand" href="#"><span class="fa fa-gg"></span> Finance Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Home")">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("About","Home")">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("userServices","Services")">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("create","Complaint")">Complaint</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("HeadLogin","Head")">Login</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Contact","Home")">Contact</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </section>
    <section class="w3l-main-slider" id="home">
        <!-- main-slider -->
        <div class="companies20-content">
            <div class="owl-one owl-carousel owl-theme">
                <div class="item">
                    <li>
                        <div class="slider-info banner-view bg bg2" data-selector=".bg.bg2">
                            <div class="banner-info">
                                <div class="container">
                                    <div class="banner-info-bg mr-auto">
                                        <h5>Meet Our Brand New Solution</h5>
                                        <p>Company  provide outstanding service through teamwork, accountability and innovation of which is reflected.</p>
                                        <a class="btn btn-secondary btn-theme2 mt-5" href="services.html"> Our Services</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </div>
                <div class="item">
                    <li>
                        <div class="slider-info  banner-view banner-top1 bg bg2" data-selector=".bg.bg2">
                            <div class="banner-info">
                                <div class="container">
                                    <div class="banner-info-bg mx-auto text-center">
                                        <h5>Consulting And Audit For Small Business</h5>
                                        <p>Company  provide outstanding service through teamwork, accountability and innovation of which is reflected.</p>
                                        <a class="btn btn-secondary btn-theme2 mt-5" href="contact.html"> Contact Us</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </div>
                <div class="item">
                    <li>
                        <div class="slider-info banner-view banner-top2 bg bg2" data-selector=".bg.bg2">
                            <div class="banner-info">
                                <div class="container">
                                    <div class="banner-info-bg ml-auto text-right">
                                        <h5>Discover The World Of Business</h5>
                                        <p>Company  provide outstanding service through teamwork, accountability and innovation of which is reflected.</p>
                                        <a class="btn btn-secondary btn-theme2 mt-5" href="about.html"> About Us</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </div>
                <div class="item">
                    <li>
                        <div class="slider-info banner-view banner-top3 bg bg2" data-selector=".bg.bg2">
                            <div class="banner-info">
                                <div class="container">
                                    <div class="banner-info-bg mr-auto">
                                        <h5>Meet Our Brand New Solution </h5>
                                        <p>Company  provide outstanding service through teamwork, accountability and innovation of which is reflected.</p>
                                        <a class="btn btn-secondary btn-theme2 mt-5" href="services.html">Read More</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                </div>
            </div>
        </div>
        </div>


        <script src="~/assets/js/owl.carousel.js"></script>
        <!-- script for -->
        <script>
    $(document).ready(function () {
                $('.owl-one').owlCarousel({
                    loop: true,
                    margin: 0,
                    nav: false,
                    responsiveClass: true,
                    autoplay: false,
                    autoplayTimeout: 5000,
                    autoplaySpeed: 1000,
                    autoplayHoverPause: false,
                    responsive: {
                        0: {
                            items: 1,
                            nav: false
                        },
                        480: {
                            items: 1,
                            nav: false
                        },
                        667: {
                            items: 1,
                            nav: true
                        },
                        1000: {
                            items: 1,
                            nav: true
                        }
                    }
                })
            })</script>

    </section>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>


    <section class="w3l-footer-29-main">
        <div class="footer-29">
            <div class="container">

                <div class="d-grid grid-col-2 bottom-copies">
                    <p class="copy-footer-29">
                        © 2020 Finance Management. All rights reserved | Deveoped by <a href="h#">Piyush</a>
                    </p>

                </div>
            </div>
        </div>
        <!-- move top -->
        <button onclick="topFunction()" id="movetop" title="Go to top">
            <span class="fa fa-angle-up"></span>
        </button>
        <script>
            // When the user scrolls down 20px from the top of the document, show the button
            window.onscroll = function () {
                scrollFunction()
            };

            function scrollFunction() {
                if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                    document.getElementById("movetop").style.display = "block";
                } else {
                    document.getElementById("movetop").style.display = "none";
                }
            }

            // When the user clicks on the button, scroll to the top of the document
            function topFunction() {
                document.body.scrollTop = 0;
                document.documentElement.scrollTop = 0;
            }
        </script>
        <!-- /move top -->
    </section>
    <script src="~/assets/js/jquery-3.3.1.min.js"></script>
    <!-- //footer-28 block -->
    </section>
    <script>
        $(function () {
            $('.navbar-toggler').click(function () {
                $('body').toggleClass('noscroll');
            })
        });
    </script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    <!-- Template JavaScript -->
    <script src="~/assets/js/all.js"></script>
    <!-- Smooth scrolling -->
    <!-- <script src="assets/js/smoothscroll.js"></script> -->
    <script src="~/assets/js/owl.carousel.js"></script>

    <!-- script for -->
    <script>
        $(document).ready(function () {
            $('.owl-one').owlCarousel({
                loop: true,
                margin: 0,
                nav: true,
                responsiveClass: true,
                autoplay: false,
                autoplayTimeout: 5000,
                autoplaySpeed: 1000,
                autoplayHoverPause: false,
                responsive: {
                    0: {
                        items: 1,
                        nav: false
                    },
                    480: {
                        items: 1,
                        nav: false
                    },
                    667: {
                        items: 1,
                        nav: true
                    },
                    1000: {
                        items: 1,
                        nav: true
                    }
                }
            })
        })
    </script>
    <!-- //script -->


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>